name: Manhunt
version: ${project.version}
main: me.ofearr.manhunt.Manhunt
api-version: 1.16
commands:
  setrunner:
    description: Set a player to be a speed runner.
    aliases: [runner, manhuntrunner]
  startgame:
    description: Start a game of manhunt.
    aliases: [startmanhunt, manhuntstart]
